export const ERROR_CODES = {
  TENANT_NOT_RESOLVED: 'TENANT_NOT_RESOLVED',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REUSED: 'TOKEN_REUSED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  FEATURE_NOT_ON_PLAN: 'FEATURE_NOT_ON_PLAN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  ATTRIBUTE_UNKNOWN: 'ATTRIBUTE_UNKNOWN',
  ATTRIBUTE_TYPE_MISMATCH: 'ATTRIBUTE_TYPE_MISMATCH',
  HARDWARE_SIGNATURE_INVALID: 'HARDWARE_SIGNATURE_INVALID',
  HARDWARE_TIMESTAMP_SKEW: 'HARDWARE_TIMESTAMP_SKEW',
  HARDWARE_UNKNOWN_DEVICE: 'HARDWARE_UNKNOWN_DEVICE',
  HARDWARE_UNKNOWN_TAG: 'HARDWARE_UNKNOWN_TAG',
  HARDWARE_NO_ACTIVE_TRIP: 'HARDWARE_NO_ACTIVE_TRIP',
  MPESA_CALLBACK_INVALID: 'MPESA_CALLBACK_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiError {
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
  requestId?: string;
}
